### ISSUE TITLE
Recommended download source?

### ISSUE THREAD

**Issue by adamjstewart** [scivision/METIS#3]
I noticed that https://github.com/scivision/METIS/raw/master/metis-5.1.0.tar.gz is no longer available for download. It is available at http://glaros.dtc.umn.edu/gkhome/metis/metis/download, with older versions available at http://glaros.dtc.umn.edu/gkhome/fsroot/sw/metis/OLD. Is there a reason 5.1.0 was removed from GitHub? I'm a developer for the [Spack](https://spack.io) package manager, so we like to have a stable download location we can rely on. Would you recommend that we download metis from GitHub or from glaros.dtc.umn.edu?

P.S. Would you or anyone else be interested in helping to maintain the Spack recipe for metis? You don't have to be an expert on Spack, it just gives us someone to ping about build issues or questions like this.

@mlawsonca

**Comment by scivision** [comment]
I'm not affiliated with METIS developers, I was just a user who was worried their website could go down. I had moved those files to https://github.com/scivision/METIS/tree/master/archive just to avoid confusion/clutter.
