### ISSUE TITLE
Integration with the latest METIS repository

### ISSUE THREAD

**Issue by adam-sim-dev** [scivision/METIS#6]
Hi @scivision ,

Is there any possibility to integrate with the latest METIS repository? 

https://github.com/KarypisLab/METIS/releases/tag/v5.2.1

Prof. Karypis has released METIS-5.2.1

Best,
Adam

**Comment by scivision** [comment]
Thanks, I will use the CMakeLists.txt injection into unmodified source like I did for scivision/scalapack, scivision/lapack and scivision/mumps, all of which are used successfully by many users. For MUMPS especially it has become quite popular.

The original METIS 5.2.1 CMake uses techniques distinct from modern CMake, that can be problematic.

**Comment by scivision** [comment]
Hmm, METIS 5.2.1 and associated GKlib have numerous code and build problems. It would take some effort to resolve these, and I wonder why the original author hasn't fixed them. It would be beyond the effort I can afford to expend to fix their METIS and GKlib libraries for METIS 5.2.0. Note I had to fix METIS 5.1.0 in several places also to get it to build previously.

**Comment by adam-sim-dev** [comment]
> Hmm, METIS 5.2.1 and associated GKlib have numerous code and build problems. It would take some effort to resolve these, and I wonder why the original author hasn't fixed them. It would be beyond the effort I can afford to expend to fix their METIS and GKlib libraries for METIS 5.2.0. Note I had to fix METIS 5.1.0 in several places also to get it to build previously.

It seems that METIS is not under active maintenance, and there are no replies to the github issues and PRs. PETSc developers host their patches to METIS-5.1.0, https://bitbucket.org/petsc/pkg-metis.git. It will be good if someone could collect all the fixes and any new features in METIS development repository together.

**Comment by adam-sim-dev** [comment]
> Thanks, I will use the CMakeLists.txt injection into unmodified source like I did for scivision/scalapack, scivision/lapack and scivision/mumps, all of which are used successfully by many users. For MUMPS especially it has become quite popular.
> 
> The original METIS 5.2.1 CMake uses techniques distinct from modern CMake, that can be problematic.

Thanks for your CMake supports for MUMPS. I have used it for my application and it is especially useful for Windows.

**Comment by scivision** [comment]
I fixed the latest GKlib after all, it turned out to be a compiler flag uptream GKlib had added that was not compatible with C89 style code.

The METIS 5.2.0 source code has an API issue, i.e. it has a header not compatible with its own source code (different number of arguments). I will see sometime perhaps over the year-end holidays if it's fixable.

**Comment by scivision** [comment]
This is now done, based on current upstream GKlib and METIS.
